package poo.campos.entity;
// Generated 09-dic-2018 15:21:15 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Campo generated by hbm2java
 */
public class Campo implements java.io.Serializable {

    private Integer id;
    private Estado estado;
    private String nombre;
    private Double superficie;
    private Set<Lote> lotes;

    public Campo() {
        lotes = new HashSet<>();
    }

    public Campo(Estado estado, String nombre, Double superficie, Set lotes) {
        this.estado = estado;
        this.nombre = nombre;
        this.superficie = superficie;
        this.lotes = lotes;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Estado getEstado() {
        return this.estado;
    }

    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Double getSuperficie() {
        return this.superficie;
    }

    public void setSuperficie(Double superficie) {
        this.superficie = superficie;
    }

    public Set getLotes() {
        return this.lotes;
    }

    public void setLotes(Set lotes) {
        this.lotes = lotes;
    }

}
