package poo.campos.entity;
// Generated 09-dic-2018 15:21:15 by Hibernate Tools 4.3.1

/**
 * Estado generated by hbm2java
 */
public class Estado implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private String descripcion;

    public Estado() {
    }

    public Estado(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}
