package poo.campos.entity;
// Generated 09-dic-2018 15:21:15 by Hibernate Tools 4.3.1

/**
 * Lote generated by hbm2java
 */
public class Lote implements java.io.Serializable {

    private Integer id;
    private TipoSuelo tiposuelo;
    private Integer nro;
    private Double superficie;

    public Lote() {
    }

    public Lote(TipoSuelo tiposuelo, Integer nro, Double superficie) {
        this.tiposuelo = tiposuelo;
        this.nro = nro;
        this.superficie = superficie;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public TipoSuelo getTiposuelo() {
        return this.tiposuelo;
    }

    public void setTiposuelo(TipoSuelo tiposuelo) {
        this.tiposuelo = tiposuelo;
    }

    public Integer getNro() {
        return this.nro;
    }

    public void setNro(Integer nro) {
        this.nro = nro;
    }

    public Double getSuperficie() {
        return this.superficie;
    }

    public void setSuperficie(Double superficie) {
        this.superficie = superficie;
    }

}
