package poo.campos.entity;
// Generated 09-dic-2018 15:21:15 by Hibernate Tools 4.3.1

import java.util.Set;

/**
 * Tiposuelo generated by hbm2java
 */
public class TipoSuelo implements java.io.Serializable {

    private Integer id;
    private Integer nro;
    private String observacion;

    public TipoSuelo() {
    }

    public TipoSuelo(Integer nro, String observacion) {
        this.nro = nro;
        this.observacion = observacion;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getNro() {
        return this.nro;
    }

    public void setNro(Integer nro) {
        this.nro = nro;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
}
